### ISSUE TITLE
补充一些用得比较多的数据库

### ISSUE THREAD

**Issue by LenJKiang** [act-china/public-datasets#1]
UK Biobank: 很出名的一个大型数据库, 拥有成像的被试高达几万, 同时拥有众多表型数据和基因数据. 但是需要申请才可以下载. https://biobank.ctsu.ox.ac.uk/
Adolescent Brain Cognitive Development (ABCD): 最近比较火的一个数据队列, 也是拥有众多表型和神经成像的数据集. 受试者比较特殊, 均是青少年. https://abcdstudy.org/index.html
ANDI: 老年痴呆症数据集, 拥有神经成像和基因数据. http://adni.loni.usc.edu/data-samples/access-data/

**Comment by younghoo** [comment]
谢谢！这些大样本数据集我也了解过，申请还是有点麻烦的，我后面添上。
